name = "solar_imperium"
main = "server/worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./dist"

[durable_objects]
bindings = [{ name = "GAME_ROOM", class_name = "GameRoom" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
